// Code generated by "stringer -type suit"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[highcard-0]
	_ = x[onepair-1]
	_ = x[twopair-2]
	_ = x[threeofkind-3]
	_ = x[fullhouse-4]
	_ = x[fourofkind-5]
	_ = x[fiveofkind-6]
}

const _suit_name = "highcardonepairtwopairthreeofkindfullhousefourofkindfiveofkind"

var _suit_index = [...]uint8{0, 8, 15, 22, 33, 42, 52, 62}

func (i suit) String() string {
	if i < 0 || i >= suit(len(_suit_index)-1) {
		return "suit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _suit_name[_suit_index[i]:_suit_index[i+1]]
}
